version: "3.9"

services:
  postgres:
    container_name: cair-postgres
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cair-db
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB_NAME || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-platform

#  redis:
#    container_name: cair-redis
#    image: redis:7-alpine
#    env_file:
#      - .env
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_USER=${REDIS_USER}
#      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
#    ports:
#      - "6380:6379"
#    volumes:
#      - redis_data:/data
#    command: >
#      sh -c '
#        mkdir -p /usr/local/etc/redis &&
#        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
#        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
#        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
#        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
#        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
#        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
#        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
#      '
#    healthcheck:
#      test: ["CMD-SHELL", "redis-cli -a $REDIS_PASSWORD ping | grep PONG || exit 1"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: unless-stopped
#    tty: true
#    stdin_open: true
#    networks:
#      - app-platform
#    deploy:
#      resources:
#        limits:
#          cpus: "0.50"
#          memory: 512M
#        reservations:
#          cpus: "0.25"
#          memory: 256M

  redis:
    container_name: cair-redis
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    container_name: cair-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS}
      - POSTGRES_ADDRESS_PORT=${POSTGRES_ADDRESS_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#        max-file: "20"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/api/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - app-platform

networks:
  app-platform:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
